import fs from 'node:fs'
import path from 'node:path'
const read=(p)=>fs.readFileSync(path.join(process.cwd(),p),'utf8')
const a=read('src/features/volunteer/pages/VolunteerAvailabilityPage.tsx')
const b=read('src/features/volunteer/pages/VolunteerAvailabilityUnavailablePage.tsx')
const p=read('src/features/volunteer/pages/PersistedVolunteerAvailabilityPage.tsx')
const s=read('src/features/volunteer/integration/persistedVolunteerAvailability.ts')
const d=read('src/features/admin/pages/AdminVolunteerEvaluatorsPage.tsx')
const detail=read('src/features/admin/pages/PersistedAdminVolunteerAccountPage.tsx')
const o=read('src/features/admin/pages/AdminAvailabilityOverridePage.tsx')
const asvc=read('src/features/admin/integration/persistedAdminVolunteerDirectory.ts')
const m=read('../supabase/migrations/20260910024000_step_vii_e2h7_volunteer_declared_availability.sql')
for(const x of ['PrototypeVolunteerAvailabilityPage','PersistedVolunteerAvailabilityPage']) if(!a.includes(x)) throw new Error('availability wrapper '+x)
for(const x of ['PrototypeVolunteerAvailabilityUnavailablePage','PersistedVolunteerAvailabilityPage']) if(!b.includes(x)) throw new Error('unavailable wrapper '+x)
for(const x of ['They cannot change or override your availability.','setPersistedVolunteerAvailability']) if(!p.includes(x)) throw new Error('persisted page '+x)
for(const x of ['svc_volunteer_get_availability','svc_volunteer_set_availability']) if(!s.includes(x)) throw new Error('service '+x)
if(!d.includes('>Availability<')) throw new Error('admin directory Availability heading')
if(!detail.includes('Availability status:')) throw new Error('admin detail Availability status:')
if(!/Admins\s+and\s+Super\s+Admins\s+can\s+view\s+it\s+only\./.test(detail)) throw new Error('admin detail read-only copy')
if(!o.includes('Configured runtime is read-only for Volunteer availability')) throw new Error('override block')
if(!asvc.includes('availability')) throw new Error('admin service availability')
for(const x of ['create table if not exists public.volunteer_availability','svc_volunteer_get_availability','svc_volunteer_set_availability','volunteer.availability_updated','svc_staff_list_volunteer_accounts','svc_staff_get_volunteer_account']) if(!m.toLowerCase().includes(x.toLowerCase())) throw new Error('migration '+x)
for(const x of ['svc_staff_set_volunteer_availability','admin_override','set_effective_availability']) if(m.toLowerCase().includes(x)) throw new Error('forbidden override '+x)
console.log('Step VII-E2H7 Volunteer-declared availability, staff read-only visibility: PASS')
