name: auratio_mobile
description: "Auratio cross-platform mobile application."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.13.1

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  flutter_riverpod: ^3.4.2
  go_router: ^18.0.0
  supabase_flutter: 2.17.2
  file_picker: 12.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/InterVariable.ttf

  assets:
    - assets/images/auratio_full_lockup.png
