// AUTO-GENERATED by portal/scripts/generate-rubric-anchors.mjs
// Source: docs/ai/rubrics-and-anchors-v1.json
// Do not hand-edit. Regenerate from the authoritative JSON.

export type QualitativeAnchor = 'Low' | 'Competent' | 'Excellent'

export interface AnchorScoreRange {
  min: number
  max: number
}

export interface CriterionAnchorDescriptions {
  Low: string
  Competent: string
  Excellent: string
}

export const CANONICAL_SCORE_RANGES = {
  "5_point": {
    "Low": {
      "min": 0,
      "max": 2
    },
    "Competent": {
      "min": 3,
      "max": 4
    },
    "Excellent": {
      "min": 5,
      "max": 5
    }
  },
  "10_point": {
    "Low": {
      "min": 0,
      "max": 4
    },
    "Competent": {
      "min": 5,
      "max": 8
    },
    "Excellent": {
      "min": 9,
      "max": 10
    }
  }
} as const

export const CRITERION_ANCHOR_DESCRIPTIONS = {
  "ud-pacing": {
    "Low": "Pace is frequently too fast, too slow, or uneven; pauses are poorly placed or absent enough to hinder comprehension or emphasis.",
    "Competent": "Pace is generally appropriate and understandable, with useful pauses and only occasional rushed, slow, or awkward sections.",
    "Excellent": "Pace is consistently well calibrated to the content and audience; pauses are deliberate, natural, and strengthen clarity and emphasis."
  },
  "ud-tone": {
    "Low": "Tone is persistently flat, mismatched, or uncontrolled, with energy that weakens meaning or audience engagement.",
    "Competent": "Tone and energy generally match the message, with noticeable modulation and only limited stretches of monotony or mismatch.",
    "Excellent": "Tone, modulation, and energy are consistently controlled, expressive, and well matched to the message without sounding exaggerated."
  },
  "ud-variety": {
    "Low": "Pitch, volume, rhythm, or emphasis vary too little or unpredictably, making delivery monotonous or distracting.",
    "Competent": "Uses enough variation in pitch, volume, rhythm, and emphasis to support meaning, though some passages remain uniform.",
    "Excellent": "Uses purposeful, natural vocal variation throughout to highlight ideas, sustain attention, and reinforce meaning."
  },
  "ud-filler": {
    "Low": "Frequent fillers, verbal resets, or uncontrolled silences noticeably disrupt fluency and clarity.",
    "Competent": "Fillers and silences are generally controlled; occasional disruptions occur but do not materially impair the message.",
    "Excellent": "Speech is consistently fluent, with minimal fillers and deliberate silence used effectively for pacing or emphasis."
  },
  "ud-eye-contact": {
    "Low": "Gaze is frequently disengaged, unstable, or fixed away from the audience/camera in ways that weaken connection.",
    "Competent": "Maintains generally stable audience/camera engagement with occasional unnecessary gaze breaks or reliance on notes.",
    "Excellent": "Maintains natural, confident, and purposeful gaze engagement, using shifts appropriately without appearing fixed or artificial."
  },
  "ud-posture": {
    "Low": "Posture or body positioning is frequently closed, unstable, distracting, or poorly aligned with effective delivery.",
    "Competent": "Posture is generally composed and appropriate, with only minor stiffness, slouching, or unnecessary repositioning.",
    "Excellent": "Posture and body positioning are consistently composed, open, balanced, and supportive of confident communication."
  },
  "ud-gestures": {
    "Low": "Gestures are absent when needed, repetitive, distracting, or disconnected from the message.",
    "Competent": "Gestures are mostly natural and relevant, with some missed opportunities or occasional repetitive/unnecessary movement.",
    "Excellent": "Gestures are consistently purposeful, natural, and well timed, reinforcing key ideas without distracting from the message."
  },
  "ud-framing": {
    "Low": "Movement or positioning frequently disrupts visibility, framing, focus, or the viewer's ability to follow the presentation.",
    "Competent": "Framing and movement are generally controlled and functional, with only minor unnecessary movement or positioning issues.",
    "Excellent": "Framing and movement are consistently controlled, intentional, and supportive of clear, professional visual delivery."
  },
  "sf-hook": {
    "Low": "Opening is weak, unclear, delayed, or disconnected from the purpose, giving little reason to attend to the message.",
    "Competent": "Opening establishes relevance or interest and leads into the topic, though it may be conventional or only moderately compelling.",
    "Excellent": "Opening captures attention quickly, establishes relevance, and creates a strong, natural bridge into the central message."
  },
  "sf-transitions": {
    "Low": "Ideas shift abruptly or illogically, making the progression difficult to follow.",
    "Competent": "Most transitions make the progression understandable, with only occasional abrupt or weak connections.",
    "Excellent": "Transitions are consistently clear, purposeful, and seamless, making the progression of ideas easy to follow."
  },
  "sf-thesis": {
    "Low": "The central point is missing, contradictory, or difficult to identify.",
    "Competent": "The central thesis is identifiable and mostly maintained, though it may be broad, delayed, or occasionally blurred.",
    "Excellent": "The central thesis is precise, easy to identify, and consistently governs the selection and organization of content."
  },
  "sf-conclusion": {
    "Low": "Ending is abrupt, repetitive, incomplete, or poorly matched to the selected track's purpose.",
    "Competent": "Conclusion provides appropriate closure and reinforces the main message, though impact or specificity may be limited.",
    "Excellent": "Conclusion provides clear, memorable, track-appropriate closure that reinforces the central message and desired takeaway or action."
  },
  "inf-clarity": {
    "Low": "The informational objective is unclear, inconsistent, or obscured by irrelevant material.",
    "Competent": "The informational objective is clear and mostly sustained, with minor drift or unnecessary material.",
    "Excellent": "The informational objective is explicit, focused, and consistently guides what information is selected and emphasized."
  },
  "inf-comprehension": {
    "Low": "Explanation assumes too much, omits key context, or presents information in ways that are difficult for the intended audience to follow.",
    "Competent": "Most information is understandable with adequate context and explanation, though some points could be made more accessible.",
    "Excellent": "Information is consistently organized and explained for easy audience comprehension, with context and emphasis placed exactly where needed."
  },
  "inf-neutrality": {
    "Low": "Presentation shows strong unsupported bias, obvious internal contradictions, or presents uncertain claims as established facts.",
    "Competent": "Presentation is mostly neutral and internally consistent, distinguishing key claims adequately with only minor overstatement or imbalance.",
    "Excellent": "Presentation is consistently neutral, precise, and internally coherent, clearly separating observation, interpretation, and uncertainty where relevant."
  },
  "inf-breakdown": {
    "Low": "Complex ideas remain dense, poorly segmented, or unexplained, leaving important relationships unclear.",
    "Competent": "Complex ideas are broken into understandable parts with useful explanation, though some steps or relationships could be clearer.",
    "Excellent": "Complex ideas are decomposed into clear, well-sequenced parts that preserve accuracy while making relationships easy to understand."
  },
  "ex-thesis": {
    "Low": "The speaker takes too long to establish a usable central point or never establishes one clearly.",
    "Competent": "A workable thesis appears reasonably early and guides most of the response, though the opening may wander briefly.",
    "Excellent": "A clear, relevant thesis is established quickly and confidently, giving immediate direction to the spontaneous response."
  },
  "ex-structure": {
    "Low": "Ideas appear improvised without a stable sequence, causing repetition, gaps, or confusion.",
    "Competent": "The response has a recognizable spontaneous structure with mostly logical sequencing despite minor roughness.",
    "Excellent": "The response feels spontaneous yet highly organized, with a clear beginning, development, and conclusion formed in real time."
  },
  "ex-narrative": {
    "Low": "The response repeatedly loses its thread, shifts topics without connection, or leaves ideas unfinished.",
    "Competent": "The main thread remains understandable with only occasional detours or weak links.",
    "Excellent": "A coherent thread is maintained throughout, with each idea naturally advancing the spontaneous narrative or argument."
  },
  "ex-composure": {
    "Low": "Frequent hesitation, visible uncertainty, or recovery difficulties materially disrupt the spontaneous response.",
    "Competent": "The speaker remains generally composed and recovers from occasional hesitation without losing the message.",
    "Excellent": "The speaker maintains strong composure under spontaneous conditions, using brief thinking pauses naturally and recovering smoothly when needed."
  },
  "per-ethos-pathos-logos": {
    "Low": "Persuasion relies heavily on one weak appeal or lacks credible, emotional, and logical support in combination.",
    "Competent": "Uses a workable mix of credibility, emotion, and reasoning, though one dimension may be underdeveloped.",
    "Excellent": "Integrates credibility, emotional resonance, and logical reasoning in a deliberate balance that strengthens the persuasive case."
  },
  "per-emotional-resonance": {
    "Low": "The message gives the audience little emotional reason to care or uses emotion in a forced or irrelevant way.",
    "Competent": "Creates relevant emotional engagement at key points, though the connection may be uneven or predictable.",
    "Excellent": "Builds authentic, audience-relevant emotional resonance that deepens attention and supports the persuasive objective."
  },
  "per-urgency-conviction": {
    "Low": "The speaker appears uncertain or gives little reason why the audience should care or act now.",
    "Competent": "Communicates believable conviction and some sense of importance or urgency, with minor inconsistency.",
    "Excellent": "Communicates sustained conviction and a compelling, proportionate sense of urgency that strengthens the call to action."
  },
  "per-objection": {
    "Low": "Ignores obvious audience objections or responds to resistance weakly, defensively, or without reasoning.",
    "Competent": "Recognizes relevant objections and addresses them with generally credible responses, though some resistance remains underdeveloped.",
    "Excellent": "Anticipates the strongest likely objections and addresses them fairly and convincingly in a way that strengthens the overall case."
  },
  "arg-premise": {
    "Low": "Claims do not follow clearly from stated premises, or key premises are missing or contradictory.",
    "Competent": "Most claims are supported by relevant premises, with only minor gaps or loosely connected reasoning.",
    "Excellent": "Claims consistently follow from clearly stated, relevant premises, producing a coherent argumentative foundation."
  },
  "arg-evidence": {
    "Low": "Evidence is sparse, vague, misapplied, or insufficiently connected to the claims it is meant to support.",
    "Competent": "Uses relevant evidence for most important claims and generally explains its significance, with some limitations in depth or precision.",
    "Excellent": "Uses specific, relevant evidence strategically and explains how it supports each major claim without overstating what the evidence proves."
  },
  "arg-validity": {
    "Low": "Reasoning contains obvious internal contradictions, unsupported leaps, or unclear argumentative signposting.",
    "Competent": "Reasoning is mostly coherent and signposted, with only minor gaps or ambiguous links.",
    "Excellent": "Reasoning is consistently coherent, explicitly signposted, and free of material internal contradictions or unsupported logical leaps."
  },
  "arg-counterarguments": {
    "Low": "Counterarguments are ignored, misrepresented, or answered with weak assertions rather than rebuttal.",
    "Competent": "Addresses relevant counterarguments fairly and offers generally plausible rebuttals, though depth may vary.",
    "Excellent": "Engages the strongest counterarguments accurately and responds with clear, proportionate rebuttals that materially strengthen the position."
  },
  "exp-simplification": {
    "Low": "Simplification is insufficient or distorts the concept, leaving the audience confused or with an inaccurate mental model.",
    "Competent": "Simplifies the concept effectively for most of the audience while preserving the essential meaning, with minor areas of unnecessary complexity.",
    "Excellent": "Makes difficult material accessible without sacrificing essential accuracy, using precisely the level of simplification the audience needs."
  },
  "exp-analogies": {
    "Low": "Analogies are absent where needed, confusing, misleading, or poorly connected to the concept.",
    "Competent": "Uses relevant analogies or mental models that aid understanding, though some may be conventional or only partially developed.",
    "Excellent": "Uses clear, accurate, and memorable analogies or mental models that materially improve understanding of difficult ideas."
  },
  "exp-jargon": {
    "Low": "Unexplained jargon or technical language repeatedly obstructs audience understanding.",
    "Competent": "Most necessary technical terms are controlled or explained, with only occasional unexplained or avoidable jargon.",
    "Excellent": "Uses technical terminology only when useful and defines or contextualizes it seamlessly for the intended audience."
  },
  "exp-deconstruction": {
    "Low": "Steps are missing, out of order, or insufficiently connected, making the process or concept hard to reconstruct.",
    "Competent": "Breaks the concept into a mostly logical sequence with enough detail to follow, though some transitions or steps could be sharper.",
    "Excellent": "Deconstructs the concept into a precise, complete, and easy-to-follow sequence in which each step clearly builds on the previous one."
  },
  "nd-cadence": {
    "Low": "Cadence is halting, sing-song, rushed, or conversational in a way that undermines clear professional news delivery.",
    "Competent": "Maintains a generally steady broadcast-style cadence with only occasional awkward phrasing or rhythm.",
    "Excellent": "Maintains a polished, natural broadcast cadence with controlled rhythm, phrasing, and emphasis throughout."
  },
  "nd-tone": {
    "Low": "Tone is overly opinionated, casual, dramatic, or uncertain for objective news delivery.",
    "Competent": "Tone is generally objective and authoritative, with minor lapses in neutrality, confidence, or proportion.",
    "Excellent": "Tone is consistently composed, objective, credible, and appropriately authoritative without sounding detached or theatrical."
  },
  "nd-signposting": {
    "Low": "Topic or headline shifts occur abruptly, leaving the audience unclear about transitions between stories or sections.",
    "Competent": "Most story or headline shifts are signposted clearly, with occasional abrupt transitions.",
    "Excellent": "Every major shift is signposted cleanly and efficiently, preserving orientation and momentum across distinct news items."
  },
  "nd-accuracy": {
    "Low": "Frequent visible corrections, contradictions, misreads, or loss of composure undermine trust in the delivery.",
    "Competent": "Delivery is mostly accurate and composed, with minor recoverable slips that do not materially disrupt understanding.",
    "Excellent": "Delivery is consistently precise and composed, with clean recovery from any minor slip and no material internal inconsistency."
  },
  "bp-problem": {
    "Low": "The problem is vague, weakly evidenced, or disconnected from the proposed solution.",
    "Competent": "The problem is understandable and the solution addresses it credibly, though the fit or urgency could be sharper.",
    "Excellent": "The problem is specific and compelling, and the solution is clearly shown to address its core causes or needs."
  },
  "bp-value": {
    "Low": "The audience cannot clearly tell what is being offered, for whom, or why it is valuable.",
    "Competent": "The offer, target user, and primary benefit are clear, though differentiation or concise articulation may be limited.",
    "Excellent": "The value proposition is concise, specific, audience-centered, and immediately communicates what is offered and why it matters."
  },
  "bp-traction": {
    "Low": "The pitch provides little observable evidence of traction, feasibility, market interest, or reasons for an investor/buyer to engage.",
    "Competent": "Provides credible indicators of traction, feasibility, or opportunity and gives the audience a reasonable basis for interest.",
    "Excellent": "Presents compelling, well-framed evidence of traction or opportunity and translates it into a strong, credible case for investor/buyer interest."
  },
  "bp-diff": {
    "Low": "The pitch does not explain how the offer differs meaningfully from alternatives or why that difference matters.",
    "Competent": "Identifies relevant differentiators and explains their value, though the competitive case may be somewhat generic or incomplete.",
    "Excellent": "Defines clear, defensible differentiation and connects it directly to customer/investor value in a way that is difficult to confuse with alternatives."
  },
  "gp-sync": {
    "Low": "Speech and visible presentation media are frequently out of sync, causing confusion or forcing the audience to reconcile mismatched information.",
    "Competent": "Speech generally aligns with the visible media, with only occasional timing or reference mismatches.",
    "Excellent": "Speech and media are tightly synchronized, with visual changes and verbal references reinforcing each other at the right moments."
  },
  "gp-continuity": {
    "Low": "Media changes fragment the narrative or introduce content without clear connection to the spoken message.",
    "Competent": "The narrative remains mostly coherent across media changes, with only minor disconnected or redundant elements.",
    "Excellent": "All media elements contribute to one coherent narrative, with each transition extending rather than interrupting the spoken message."
  },
  "gp-visual": {
    "Low": "The speaker relies heavily on reading visible text or uses visuals that add little beyond duplicating speech.",
    "Competent": "Visuals generally support rather than replace the spoken message, with occasional over-reliance on reading or duplication.",
    "Excellent": "Visuals add complementary information while the speaker explains, interprets, or contextualizes them without simply reading them aloud."
  },
  "gp-pacing": {
    "Low": "Visual/media changes are too fast, too slow, dense, or poorly timed for the audience to process comfortably.",
    "Competent": "Media pacing is generally manageable and accessible, with only occasional rushed, delayed, or overly dense moments.",
    "Excellent": "Media pacing consistently gives the audience enough time and context to process each visual element without interrupting presentation momentum."
  },
  "ap-terminology": {
    "Low": "Specialized terms are used inaccurately, inconsistently, or without enough explanation for the intended academic audience.",
    "Competent": "Terminology is mostly precise and appropriate, with minor imprecision or occasional missed explanation.",
    "Excellent": "Specialized terminology is consistently precise, contextually appropriate, and explained whenever audience comprehension requires it."
  },
  "ap-methodology": {
    "Low": "The presented method is unclear, internally inconsistent, or insufficiently justified for the stated objective.",
    "Competent": "The method is understandable and reasonably justified, with most key design choices explained well enough to defend.",
    "Excellent": "The method is presented clearly and defensibly, with key choices, limitations, and their relationship to the objective articulated precisely."
  },
  "ap-evidence": {
    "Low": "Important claims lack visible/mentioned support, evidence is poorly connected to claims, or attribution is materially unclear.",
    "Competent": "Most important claims are supported with relevant evidence or attribution, with minor gaps in precision or integration.",
    "Excellent": "Evidence and attribution are used consistently and precisely, with clear links between sources/data and the claims they support."
  },
  "ap-findings": {
    "Low": "Findings are unclear, overstated, or disconnected from the evidence/method presented.",
    "Competent": "Findings are understandable and mostly supported by the presented evidence, with minor overreach or under-explanation.",
    "Excellent": "Findings are stated precisely, proportionately, and directly tied to the presented evidence and methodological context."
  },
  "cr-bluf": {
    "Low": "The main business conclusion or decision need is delayed, buried, or unclear.",
    "Competent": "The main conclusion or decision need appears early enough and guides most of the report, though it could be sharper.",
    "Excellent": "The key conclusion, implication, or decision need is presented immediately and clearly, giving the audience a strong frame for everything that follows."
  },
  "cr-translation": {
    "Low": "Data is recited or shown without sufficient interpretation, leaving business meaning unclear.",
    "Competent": "Most data is translated into understandable business meaning, though some figures remain insufficiently interpreted.",
    "Excellent": "Complex data is consistently converted into concise, decision-relevant meaning without losing important nuance."
  },
  "cr-insight": {
    "Low": "Observations remain descriptive and do not lead to useful implications or actions.",
    "Competent": "Identifies useful business implications and some actionable insights, though prioritization or specificity may be limited.",
    "Excellent": "Extracts clear, prioritized, actionable insights that directly connect evidence to business implications."
  },
  "cr-recommendation": {
    "Low": "Recommendations are absent, vague, unsupported, or not framed as decisions.",
    "Competent": "Provides practical recommendations linked to the presented analysis, though trade-offs or priorities may be underdeveloped.",
    "Excellent": "Provides specific, prioritized, decision-ready recommendations clearly justified by the presented evidence and business context."
  },
  "info-balance": {
    "Low": "Entertainment overwhelms useful information, or information is delivered so dryly that the intended infotainment format is not achieved.",
    "Competent": "Maintains a workable balance between useful information and entertainment, with occasional imbalance.",
    "Excellent": "Integrates information and entertainment seamlessly so each strengthens the other without sacrificing clarity or substance."
  },
  "info-progression": {
    "Low": "Progression drags, jumps erratically, or repeats material, weakening momentum.",
    "Competent": "Maintains generally brisk progression with a coherent sequence, despite occasional slow or abrupt sections.",
    "Excellent": "Maintains energetic, coherent progression throughout, moving quickly without sacrificing comprehension."
  },
  "info-triggers": {
    "Low": "Uses few meaningful devices to renew attention, or uses hooks/cues that feel repetitive or disconnected.",
    "Competent": "Uses relevant questions, contrasts, reveals, examples, or other engagement devices at useful points, though impact varies.",
    "Excellent": "Uses varied, well-timed engagement triggers that repeatedly renew attention while advancing the informational purpose."
  },
  "info-energy": {
    "Low": "On-camera presence is persistently flat, forced, or visually disengaged in ways that weaken the intended content style.",
    "Competent": "Shows an engaging, appropriate personality and visual energy with only occasional flat or overdone moments.",
    "Excellent": "Sustains an authentic, distinctive, and visually engaging presence that strengthens the content without overpowering the information."
  },
  "al-outcomes": {
    "Low": "Learners are not given a clear sense of what they should understand or be able to do.",
    "Competent": "Learning outcomes are mostly clear and reflected in the content, though they may be broad or not consistently signposted.",
    "Excellent": "Learning outcomes are explicit, focused, and visibly guide the content, examples, and final takeaway."
  },
  "al-sequence": {
    "Low": "Instruction is poorly ordered, skips prerequisites, or introduces ideas before needed foundations.",
    "Competent": "Instruction follows a mostly logical learning sequence with adequate scaffolding and only minor ordering issues.",
    "Excellent": "Instruction is deliberately scaffolded from prerequisite knowledge to more complex understanding, with each stage preparing for the next."
  },
  "al-checkin": {
    "Low": "The speaker advances without meaningful pauses, recaps, questions, or checks that help learners consolidate understanding.",
    "Competent": "Includes useful check-ins or recaps at several appropriate points, though timing or consistency could improve.",
    "Excellent": "Uses well-timed, purposeful check-ins, recaps, or reflective prompts that help learners consolidate understanding before progressing."
  },
  "al-takeaway": {
    "Low": "The lesson ends without a clear synthesis of what learners should retain or apply.",
    "Competent": "Provides a clear summary or takeaway that captures most essential learning, though application may be somewhat general.",
    "Excellent": "Ends with a concise, memorable synthesis that clearly states what learners should retain, connect, or apply next."
  },
  "mkt-painpoint": {
    "Low": "The audience problem is vague, generic, or poorly connected to the target audience's observable needs.",
    "Competent": "Identifies a relevant audience pain point and connects it reasonably to the offer, though specificity or urgency may be limited.",
    "Excellent": "Frames a specific, audience-relevant pain point compellingly and makes its importance immediately clear."
  },
  "mkt-payoff": {
    "Low": "The audience cannot clearly tell what benefit or outcome the product/service provides.",
    "Competent": "The primary payoff is understandable and relevant, though some benefits are generic or insufficiently prioritized.",
    "Excellent": "Communicates a specific, credible, audience-centered payoff that makes the value of the product/service immediately understandable."
  },
  "mkt-drivers": {
    "Low": "The presentation lacks a clear reason, incentive, proof point, or call that would move the audience toward action.",
    "Competent": "Uses relevant conversion drivers such as proof, urgency, benefits, or calls to action, though effectiveness or integration varies.",
    "Excellent": "Combines persuasive conversion drivers strategically and ethically to create a clear, credible path from interest to action."
  },
  "mkt-alignment": {
    "Low": "Tone, claims, positioning, or call to action feel inconsistent with the presented brand or offer.",
    "Competent": "Message is generally consistent with the presented brand/offer, with only minor tonal or positioning mismatches.",
    "Excellent": "Tone, value proposition, claims, and call to action are consistently aligned with a coherent brand/offer identity throughout."
  }
} as const

export const CANONICAL_CRITERION_COUNT = 64
export const CANONICAL_ANCHOR_DESCRIPTION_COUNT = 192

export function isQualitativeAnchor(value: unknown): value is QualitativeAnchor {
  return value === 'Low' || value === 'Competent' || value === 'Excellent'
}

export function getAnchorScoreRange(
  maxPoints: number,
  anchor: QualitativeAnchor | null | undefined
): AnchorScoreRange | null {
  if (!anchor || !isQualitativeAnchor(anchor)) return null
  const key = maxPoints === 5 ? '5_point' : maxPoints === 10 ? '10_point' : null
  if (!key) return null
  return CANONICAL_SCORE_RANGES[key][anchor]
}

export function isAnchorScoreCompatible(
  maxPoints: number,
  anchor: QualitativeAnchor | null | undefined,
  score: number | null | undefined
): boolean {
  if (score === null || score === undefined || !Number.isInteger(score)) return false
  const range = getAnchorScoreRange(maxPoints, anchor)
  return range !== null && score >= range.min && score <= range.max
}

export function formatAnchorScoreRange(
  maxPoints: number,
  anchor: QualitativeAnchor | null | undefined
): string {
  const range = getAnchorScoreRange(maxPoints, anchor)
  if (!range) return ''
  return range.min === range.max ? String(range.min) : `${range.min}–${range.max}`
}

export function getAnchorScoreValidationMessage(
  maxPoints: number,
  anchor: QualitativeAnchor
): string {
  const range = getAnchorScoreRange(maxPoints, anchor)
  if (!range) return 'Selected anchor is not valid for this criterion.'
  if (range.min === range.max) {
    return `${anchor} requires a score of ${range.min} for this criterion.`
  }
  return `${anchor} requires a score between ${range.min} and ${range.max} for this criterion.`
}

export function getCriterionAnchorDescriptions(
  criterionId: string
): CriterionAnchorDescriptions | null {
  const registry = CRITERION_ANCHOR_DESCRIPTIONS as Record<string, CriterionAnchorDescriptions>
  return registry[criterionId] ?? null
}
