-- Auratio Step V — canonical reference seed v1.0

insert into public.paths (id,name,sort_order) values

('public-speaking','Public Speaking',1),
('professional-presenting','Professional Presenting',2),
('content-creation','Content Creation',3);

insert into public.tracks (id,path_id,name,min_duration_seconds,max_duration_seconds,sort_order) values

('informative','public-speaking','Informative',270,450,1),
('extempore','public-speaking','Extempore',90,210,2),
('persuasive','public-speaking','Persuasive',270,450,3),
('argumentative-debate','public-speaking','Argumentative / Debate',210,390,4),
('explanatory','public-speaking','Explanatory',270,450,5),
('news-delivery','professional-presenting','News Delivery',30,210,1),
('business-pitch','professional-presenting','Business Pitch / Sales Pitch',150,330,2),
('general-presentation-multimedia','professional-presenting','General Presentation / Multimedia',330,630,3),
('academic-poster-project-thesis','professional-presenting','Academic — Poster / Project / Thesis',450,930,4),
('corporate-report','professional-presenting','Corporate Report',270,630,5),
('infotainment-oriented','content-creation','Infotainment-Oriented',30,210,1),
('academic-lecture-course','content-creation','Academic — Lecture / Course',450,1230,2),
('marketing-promotional','content-creation','Marketing / Promotional',30,150,3);

insert into public.criteria (id,name,category,max_points,track_id,position,rubric_version) values

('ud-pacing','Pacing, WPM calibration, and pause placement','universal_delivery'::public.criterion_category,5,null,1,'1.0'),
('ud-tone','Tone, modulation, and energy','universal_delivery'::public.criterion_category,5,null,2,'1.0'),
('ud-variety','Vocal variety','universal_delivery'::public.criterion_category,5,null,3,'1.0'),
('ud-filler','Filler-word and silence control','universal_delivery'::public.criterion_category,5,null,4,'1.0'),
('ud-eye-contact','Eye contact and gaze stability','universal_delivery'::public.criterion_category,5,null,5,'1.0'),
('ud-posture','Posture and body positioning','universal_delivery'::public.criterion_category,5,null,6,'1.0'),
('ud-gestures','Purposeful gestures','universal_delivery'::public.criterion_category,5,null,7,'1.0'),
('ud-framing','Framing and movement control','universal_delivery'::public.criterion_category,5,null,8,'1.0'),
('sf-hook','Hook strength','structural_flow'::public.criterion_category,5,null,1,'1.0'),
('sf-transitions','Logical transitions','structural_flow'::public.criterion_category,5,null,2,'1.0'),
('sf-thesis','Central thesis clarity','structural_flow'::public.criterion_category,5,null,3,'1.0'),
('sf-conclusion','Track-appropriate conclusion','structural_flow'::public.criterion_category,5,null,4,'1.0'),
('inf-clarity','Objective clarity','track_specialisation'::public.criterion_category,10,'informative',1,'1.0'),
('inf-comprehension','Audience comprehension','track_specialisation'::public.criterion_category,10,'informative',2,'1.0'),
('inf-neutrality','Neutrality and factual accuracy','track_specialisation'::public.criterion_category,10,'informative',3,'1.0'),
('inf-breakdown','Complex concept breakdown','track_specialisation'::public.criterion_category,10,'informative',4,'1.0'),
('ex-thesis','Rapid time-to-thesis','track_specialisation'::public.criterion_category,10,'extempore',1,'1.0'),
('ex-structure','Spontaneous structure','track_specialisation'::public.criterion_category,10,'extempore',2,'1.0'),
('ex-narrative','Narrative continuity','track_specialisation'::public.criterion_category,10,'extempore',3,'1.0'),
('ex-composure','Composure and hesitation control','track_specialisation'::public.criterion_category,10,'extempore',4,'1.0'),
('per-ethos-pathos-logos','Ethos, Pathos, and Logos balance','track_specialisation'::public.criterion_category,10,'persuasive',1,'1.0'),
('per-emotional-resonance','Audience emotional resonance','track_specialisation'::public.criterion_category,10,'persuasive',2,'1.0'),
('per-urgency-conviction','Urgency and conviction','track_specialisation'::public.criterion_category,10,'persuasive',3,'1.0'),
('per-objection','Objection anticipation and resistance handling','track_specialisation'::public.criterion_category,10,'persuasive',4,'1.0'),
('arg-premise','Premise-claim alignment','track_specialisation'::public.criterion_category,10,'argumentative-debate',1,'1.0'),
('arg-evidence','Evidence rigour','track_specialisation'::public.criterion_category,10,'argumentative-debate',2,'1.0'),
('arg-validity','Logical validity and signposting','track_specialisation'::public.criterion_category,10,'argumentative-debate',3,'1.0'),
('arg-counterarguments','Counterarguments and rebuttals','track_specialisation'::public.criterion_category,10,'argumentative-debate',4,'1.0'),
('exp-simplification','Pedagogical simplification','track_specialisation'::public.criterion_category,10,'explanatory',1,'1.0'),
('exp-analogies','Analogies and mental models','track_specialisation'::public.criterion_category,10,'explanatory',2,'1.0'),
('exp-jargon','Jargon control','track_specialisation'::public.criterion_category,10,'explanatory',3,'1.0'),
('exp-deconstruction','Step-by-step deconstruction','track_specialisation'::public.criterion_category,10,'explanatory',4,'1.0'),
('nd-cadence','Teleprompter-style cadence','track_specialisation'::public.criterion_category,10,'news-delivery',1,'1.0'),
('nd-tone','Objective authoritative tone','track_specialisation'::public.criterion_category,10,'news-delivery',2,'1.0'),
('nd-signposting','Headline-shift signposting','track_specialisation'::public.criterion_category,10,'news-delivery',3,'1.0'),
('nd-accuracy','Accuracy and composure','track_specialisation'::public.criterion_category,10,'news-delivery',4,'1.0'),
('bp-problem','Problem-solution fit','track_specialisation'::public.criterion_category,10,'business-pitch',1,'1.0'),
('bp-value','Value proposition clarity','track_specialisation'::public.criterion_category,10,'business-pitch',2,'1.0'),
('bp-traction','Traction and investor appeal','track_specialisation'::public.criterion_category,10,'business-pitch',3,'1.0'),
('bp-diff','Competitive differentiation','track_specialisation'::public.criterion_category,10,'business-pitch',4,'1.0'),
('gp-sync','Slide-to-speech synchronisation','track_specialisation'::public.criterion_category,10,'general-presentation-multimedia',1,'1.0'),
('gp-continuity','Narrative continuity across media','track_specialisation'::public.criterion_category,10,'general-presentation-multimedia',2,'1.0'),
('gp-visual','Visual support without reading','track_specialisation'::public.criterion_category,10,'general-presentation-multimedia',3,'1.0'),
('gp-pacing','Media pacing and accessibility','track_specialisation'::public.criterion_category,10,'general-presentation-multimedia',4,'1.0'),
('ap-terminology','Specialised terminology precision','track_specialisation'::public.criterion_category,10,'academic-poster-project-thesis',1,'1.0'),
('ap-methodology','Methodology defensibility','track_specialisation'::public.criterion_category,10,'academic-poster-project-thesis',2,'1.0'),
('ap-evidence','Citation and evidence rigour','track_specialisation'::public.criterion_category,10,'academic-poster-project-thesis',3,'1.0'),
('ap-findings','Findings and claim support','track_specialisation'::public.criterion_category,10,'academic-poster-project-thesis',4,'1.0'),
('cr-bluf','Bottom-Line Up Front orientation','track_specialisation'::public.criterion_category,10,'corporate-report',1,'1.0'),
('cr-translation','Complex data translation','track_specialisation'::public.criterion_category,10,'corporate-report',2,'1.0'),
('cr-insight','Actionable business insight','track_specialisation'::public.criterion_category,10,'corporate-report',3,'1.0'),
('cr-recommendation','Decision-oriented recommendation','track_specialisation'::public.criterion_category,10,'corporate-report',4,'1.0'),
('info-balance','Information-entertainment balance','track_specialisation'::public.criterion_category,10,'infotainment-oriented',1,'1.0'),
('info-progression','Fast-paced narrative progression','track_specialisation'::public.criterion_category,10,'infotainment-oriented',2,'1.0'),
('info-triggers','Engagement triggers','track_specialisation'::public.criterion_category,10,'infotainment-oriented',3,'1.0'),
('info-energy','Personality and visual energy','track_specialisation'::public.criterion_category,10,'infotainment-oriented',4,'1.0'),
('al-outcomes','Structured learning outcomes','track_specialisation'::public.criterion_category,10,'academic-lecture-course',1,'1.0'),
('al-sequence','Instructional sequence','track_specialisation'::public.criterion_category,10,'academic-lecture-course',2,'1.0'),
('al-checkin','Concept check-in pacing','track_specialisation'::public.criterion_category,10,'academic-lecture-course',3,'1.0'),
('al-takeaway','Instructional takeaway clarity','track_specialisation'::public.criterion_category,10,'academic-lecture-course',4,'1.0'),
('mkt-painpoint','Audience pain-point positioning','track_specialisation'::public.criterion_category,10,'marketing-promotional',1,'1.0'),
('mkt-payoff','Product or service payoff clarity','track_specialisation'::public.criterion_category,10,'marketing-promotional',2,'1.0'),
('mkt-drivers','Conversion drivers','track_specialisation'::public.criterion_category,10,'marketing-promotional',3,'1.0'),
('mkt-alignment','Brand-message alignment','track_specialisation'::public.criterion_category,10,'marketing-promotional',4,'1.0');

insert into public.criterion_anchors (criterion_id,anchor,description,min_score,max_score) values

('ud-pacing','Low'::public.anchor_level,'Pace is frequently too fast, too slow, or uneven; pauses are poorly placed or absent enough to hinder comprehension or emphasis.',0,2),
('ud-pacing','Competent'::public.anchor_level,'Pace is generally appropriate and understandable, with useful pauses and only occasional rushed, slow, or awkward sections.',3,4),
('ud-pacing','Excellent'::public.anchor_level,'Pace is consistently well calibrated to the content and audience; pauses are deliberate, natural, and strengthen clarity and emphasis.',5,5),
('ud-tone','Low'::public.anchor_level,'Tone is persistently flat, mismatched, or uncontrolled, with energy that weakens meaning or audience engagement.',0,2),
('ud-tone','Competent'::public.anchor_level,'Tone and energy generally match the message, with noticeable modulation and only limited stretches of monotony or mismatch.',3,4),
('ud-tone','Excellent'::public.anchor_level,'Tone, modulation, and energy are consistently controlled, expressive, and well matched to the message without sounding exaggerated.',5,5),
('ud-variety','Low'::public.anchor_level,'Pitch, volume, rhythm, or emphasis vary too little or unpredictably, making delivery monotonous or distracting.',0,2),
('ud-variety','Competent'::public.anchor_level,'Uses enough variation in pitch, volume, rhythm, and emphasis to support meaning, though some passages remain uniform.',3,4),
('ud-variety','Excellent'::public.anchor_level,'Uses purposeful, natural vocal variation throughout to highlight ideas, sustain attention, and reinforce meaning.',5,5),
('ud-filler','Low'::public.anchor_level,'Frequent fillers, verbal resets, or uncontrolled silences noticeably disrupt fluency and clarity.',0,2),
('ud-filler','Competent'::public.anchor_level,'Fillers and silences are generally controlled; occasional disruptions occur but do not materially impair the message.',3,4),
('ud-filler','Excellent'::public.anchor_level,'Speech is consistently fluent, with minimal fillers and deliberate silence used effectively for pacing or emphasis.',5,5),
('ud-eye-contact','Low'::public.anchor_level,'Gaze is frequently disengaged, unstable, or fixed away from the audience/camera in ways that weaken connection.',0,2),
('ud-eye-contact','Competent'::public.anchor_level,'Maintains generally stable audience/camera engagement with occasional unnecessary gaze breaks or reliance on notes.',3,4),
('ud-eye-contact','Excellent'::public.anchor_level,'Maintains natural, confident, and purposeful gaze engagement, using shifts appropriately without appearing fixed or artificial.',5,5),
('ud-posture','Low'::public.anchor_level,'Posture or body positioning is frequently closed, unstable, distracting, or poorly aligned with effective delivery.',0,2),
('ud-posture','Competent'::public.anchor_level,'Posture is generally composed and appropriate, with only minor stiffness, slouching, or unnecessary repositioning.',3,4),
('ud-posture','Excellent'::public.anchor_level,'Posture and body positioning are consistently composed, open, balanced, and supportive of confident communication.',5,5),
('ud-gestures','Low'::public.anchor_level,'Gestures are absent when needed, repetitive, distracting, or disconnected from the message.',0,2),
('ud-gestures','Competent'::public.anchor_level,'Gestures are mostly natural and relevant, with some missed opportunities or occasional repetitive/unnecessary movement.',3,4),
('ud-gestures','Excellent'::public.anchor_level,'Gestures are consistently purposeful, natural, and well timed, reinforcing key ideas without distracting from the message.',5,5),
('ud-framing','Low'::public.anchor_level,'Movement or positioning frequently disrupts visibility, framing, focus, or the viewer''s ability to follow the presentation.',0,2),
('ud-framing','Competent'::public.anchor_level,'Framing and movement are generally controlled and functional, with only minor unnecessary movement or positioning issues.',3,4),
('ud-framing','Excellent'::public.anchor_level,'Framing and movement are consistently controlled, intentional, and supportive of clear, professional visual delivery.',5,5),
('sf-hook','Low'::public.anchor_level,'Opening is weak, unclear, delayed, or disconnected from the purpose, giving little reason to attend to the message.',0,2),
('sf-hook','Competent'::public.anchor_level,'Opening establishes relevance or interest and leads into the topic, though it may be conventional or only moderately compelling.',3,4),
('sf-hook','Excellent'::public.anchor_level,'Opening captures attention quickly, establishes relevance, and creates a strong, natural bridge into the central message.',5,5),
('sf-transitions','Low'::public.anchor_level,'Ideas shift abruptly or illogically, making the progression difficult to follow.',0,2),
('sf-transitions','Competent'::public.anchor_level,'Most transitions make the progression understandable, with only occasional abrupt or weak connections.',3,4),
('sf-transitions','Excellent'::public.anchor_level,'Transitions are consistently clear, purposeful, and seamless, making the progression of ideas easy to follow.',5,5),
('sf-thesis','Low'::public.anchor_level,'The central point is missing, contradictory, or difficult to identify.',0,2),
('sf-thesis','Competent'::public.anchor_level,'The central thesis is identifiable and mostly maintained, though it may be broad, delayed, or occasionally blurred.',3,4),
('sf-thesis','Excellent'::public.anchor_level,'The central thesis is precise, easy to identify, and consistently governs the selection and organization of content.',5,5),
('sf-conclusion','Low'::public.anchor_level,'Ending is abrupt, repetitive, incomplete, or poorly matched to the selected track''s purpose.',0,2),
('sf-conclusion','Competent'::public.anchor_level,'Conclusion provides appropriate closure and reinforces the main message, though impact or specificity may be limited.',3,4),
('sf-conclusion','Excellent'::public.anchor_level,'Conclusion provides clear, memorable, track-appropriate closure that reinforces the central message and desired takeaway or action.',5,5),
('inf-clarity','Low'::public.anchor_level,'The informational objective is unclear, inconsistent, or obscured by irrelevant material.',0,4),
('inf-clarity','Competent'::public.anchor_level,'The informational objective is clear and mostly sustained, with minor drift or unnecessary material.',5,8),
('inf-clarity','Excellent'::public.anchor_level,'The informational objective is explicit, focused, and consistently guides what information is selected and emphasized.',9,10),
('inf-comprehension','Low'::public.anchor_level,'Explanation assumes too much, omits key context, or presents information in ways that are difficult for the intended audience to follow.',0,4),
('inf-comprehension','Competent'::public.anchor_level,'Most information is understandable with adequate context and explanation, though some points could be made more accessible.',5,8),
('inf-comprehension','Excellent'::public.anchor_level,'Information is consistently organized and explained for easy audience comprehension, with context and emphasis placed exactly where needed.',9,10),
('inf-neutrality','Low'::public.anchor_level,'Presentation shows strong unsupported bias, obvious internal contradictions, or presents uncertain claims as established facts.',0,4),
('inf-neutrality','Competent'::public.anchor_level,'Presentation is mostly neutral and internally consistent, distinguishing key claims adequately with only minor overstatement or imbalance.',5,8),
('inf-neutrality','Excellent'::public.anchor_level,'Presentation is consistently neutral, precise, and internally coherent, clearly separating observation, interpretation, and uncertainty where relevant.',9,10),
('inf-breakdown','Low'::public.anchor_level,'Complex ideas remain dense, poorly segmented, or unexplained, leaving important relationships unclear.',0,4),
('inf-breakdown','Competent'::public.anchor_level,'Complex ideas are broken into understandable parts with useful explanation, though some steps or relationships could be clearer.',5,8),
('inf-breakdown','Excellent'::public.anchor_level,'Complex ideas are decomposed into clear, well-sequenced parts that preserve accuracy while making relationships easy to understand.',9,10),
('ex-thesis','Low'::public.anchor_level,'The speaker takes too long to establish a usable central point or never establishes one clearly.',0,4),
('ex-thesis','Competent'::public.anchor_level,'A workable thesis appears reasonably early and guides most of the response, though the opening may wander briefly.',5,8),
('ex-thesis','Excellent'::public.anchor_level,'A clear, relevant thesis is established quickly and confidently, giving immediate direction to the spontaneous response.',9,10),
('ex-structure','Low'::public.anchor_level,'Ideas appear improvised without a stable sequence, causing repetition, gaps, or confusion.',0,4),
('ex-structure','Competent'::public.anchor_level,'The response has a recognizable spontaneous structure with mostly logical sequencing despite minor roughness.',5,8),
('ex-structure','Excellent'::public.anchor_level,'The response feels spontaneous yet highly organized, with a clear beginning, development, and conclusion formed in real time.',9,10),
('ex-narrative','Low'::public.anchor_level,'The response repeatedly loses its thread, shifts topics without connection, or leaves ideas unfinished.',0,4),
('ex-narrative','Competent'::public.anchor_level,'The main thread remains understandable with only occasional detours or weak links.',5,8),
('ex-narrative','Excellent'::public.anchor_level,'A coherent thread is maintained throughout, with each idea naturally advancing the spontaneous narrative or argument.',9,10),
('ex-composure','Low'::public.anchor_level,'Frequent hesitation, visible uncertainty, or recovery difficulties materially disrupt the spontaneous response.',0,4),
('ex-composure','Competent'::public.anchor_level,'The speaker remains generally composed and recovers from occasional hesitation without losing the message.',5,8),
('ex-composure','Excellent'::public.anchor_level,'The speaker maintains strong composure under spontaneous conditions, using brief thinking pauses naturally and recovering smoothly when needed.',9,10),
('per-ethos-pathos-logos','Low'::public.anchor_level,'Persuasion relies heavily on one weak appeal or lacks credible, emotional, and logical support in combination.',0,4),
('per-ethos-pathos-logos','Competent'::public.anchor_level,'Uses a workable mix of credibility, emotion, and reasoning, though one dimension may be underdeveloped.',5,8),
('per-ethos-pathos-logos','Excellent'::public.anchor_level,'Integrates credibility, emotional resonance, and logical reasoning in a deliberate balance that strengthens the persuasive case.',9,10),
('per-emotional-resonance','Low'::public.anchor_level,'The message gives the audience little emotional reason to care or uses emotion in a forced or irrelevant way.',0,4),
('per-emotional-resonance','Competent'::public.anchor_level,'Creates relevant emotional engagement at key points, though the connection may be uneven or predictable.',5,8),
('per-emotional-resonance','Excellent'::public.anchor_level,'Builds authentic, audience-relevant emotional resonance that deepens attention and supports the persuasive objective.',9,10),
('per-urgency-conviction','Low'::public.anchor_level,'The speaker appears uncertain or gives little reason why the audience should care or act now.',0,4),
('per-urgency-conviction','Competent'::public.anchor_level,'Communicates believable conviction and some sense of importance or urgency, with minor inconsistency.',5,8),
('per-urgency-conviction','Excellent'::public.anchor_level,'Communicates sustained conviction and a compelling, proportionate sense of urgency that strengthens the call to action.',9,10),
('per-objection','Low'::public.anchor_level,'Ignores obvious audience objections or responds to resistance weakly, defensively, or without reasoning.',0,4),
('per-objection','Competent'::public.anchor_level,'Recognizes relevant objections and addresses them with generally credible responses, though some resistance remains underdeveloped.',5,8),
('per-objection','Excellent'::public.anchor_level,'Anticipates the strongest likely objections and addresses them fairly and convincingly in a way that strengthens the overall case.',9,10),
('arg-premise','Low'::public.anchor_level,'Claims do not follow clearly from stated premises, or key premises are missing or contradictory.',0,4),
('arg-premise','Competent'::public.anchor_level,'Most claims are supported by relevant premises, with only minor gaps or loosely connected reasoning.',5,8),
('arg-premise','Excellent'::public.anchor_level,'Claims consistently follow from clearly stated, relevant premises, producing a coherent argumentative foundation.',9,10),
('arg-evidence','Low'::public.anchor_level,'Evidence is sparse, vague, misapplied, or insufficiently connected to the claims it is meant to support.',0,4),
('arg-evidence','Competent'::public.anchor_level,'Uses relevant evidence for most important claims and generally explains its significance, with some limitations in depth or precision.',5,8),
('arg-evidence','Excellent'::public.anchor_level,'Uses specific, relevant evidence strategically and explains how it supports each major claim without overstating what the evidence proves.',9,10),
('arg-validity','Low'::public.anchor_level,'Reasoning contains obvious internal contradictions, unsupported leaps, or unclear argumentative signposting.',0,4),
('arg-validity','Competent'::public.anchor_level,'Reasoning is mostly coherent and signposted, with only minor gaps or ambiguous links.',5,8),
('arg-validity','Excellent'::public.anchor_level,'Reasoning is consistently coherent, explicitly signposted, and free of material internal contradictions or unsupported logical leaps.',9,10),
('arg-counterarguments','Low'::public.anchor_level,'Counterarguments are ignored, misrepresented, or answered with weak assertions rather than rebuttal.',0,4),
('arg-counterarguments','Competent'::public.anchor_level,'Addresses relevant counterarguments fairly and offers generally plausible rebuttals, though depth may vary.',5,8),
('arg-counterarguments','Excellent'::public.anchor_level,'Engages the strongest counterarguments accurately and responds with clear, proportionate rebuttals that materially strengthen the position.',9,10),
('exp-simplification','Low'::public.anchor_level,'Simplification is insufficient or distorts the concept, leaving the audience confused or with an inaccurate mental model.',0,4),
('exp-simplification','Competent'::public.anchor_level,'Simplifies the concept effectively for most of the audience while preserving the essential meaning, with minor areas of unnecessary complexity.',5,8),
('exp-simplification','Excellent'::public.anchor_level,'Makes difficult material accessible without sacrificing essential accuracy, using precisely the level of simplification the audience needs.',9,10),
('exp-analogies','Low'::public.anchor_level,'Analogies are absent where needed, confusing, misleading, or poorly connected to the concept.',0,4),
('exp-analogies','Competent'::public.anchor_level,'Uses relevant analogies or mental models that aid understanding, though some may be conventional or only partially developed.',5,8),
('exp-analogies','Excellent'::public.anchor_level,'Uses clear, accurate, and memorable analogies or mental models that materially improve understanding of difficult ideas.',9,10),
('exp-jargon','Low'::public.anchor_level,'Unexplained jargon or technical language repeatedly obstructs audience understanding.',0,4),
('exp-jargon','Competent'::public.anchor_level,'Most necessary technical terms are controlled or explained, with only occasional unexplained or avoidable jargon.',5,8),
('exp-jargon','Excellent'::public.anchor_level,'Uses technical terminology only when useful and defines or contextualizes it seamlessly for the intended audience.',9,10),
('exp-deconstruction','Low'::public.anchor_level,'Steps are missing, out of order, or insufficiently connected, making the process or concept hard to reconstruct.',0,4),
('exp-deconstruction','Competent'::public.anchor_level,'Breaks the concept into a mostly logical sequence with enough detail to follow, though some transitions or steps could be sharper.',5,8),
('exp-deconstruction','Excellent'::public.anchor_level,'Deconstructs the concept into a precise, complete, and easy-to-follow sequence in which each step clearly builds on the previous one.',9,10),
('nd-cadence','Low'::public.anchor_level,'Cadence is halting, sing-song, rushed, or conversational in a way that undermines clear professional news delivery.',0,4),
('nd-cadence','Competent'::public.anchor_level,'Maintains a generally steady broadcast-style cadence with only occasional awkward phrasing or rhythm.',5,8),
('nd-cadence','Excellent'::public.anchor_level,'Maintains a polished, natural broadcast cadence with controlled rhythm, phrasing, and emphasis throughout.',9,10),
('nd-tone','Low'::public.anchor_level,'Tone is overly opinionated, casual, dramatic, or uncertain for objective news delivery.',0,4),
('nd-tone','Competent'::public.anchor_level,'Tone is generally objective and authoritative, with minor lapses in neutrality, confidence, or proportion.',5,8),
('nd-tone','Excellent'::public.anchor_level,'Tone is consistently composed, objective, credible, and appropriately authoritative without sounding detached or theatrical.',9,10),
('nd-signposting','Low'::public.anchor_level,'Topic or headline shifts occur abruptly, leaving the audience unclear about transitions between stories or sections.',0,4),
('nd-signposting','Competent'::public.anchor_level,'Most story or headline shifts are signposted clearly, with occasional abrupt transitions.',5,8),
('nd-signposting','Excellent'::public.anchor_level,'Every major shift is signposted cleanly and efficiently, preserving orientation and momentum across distinct news items.',9,10),
('nd-accuracy','Low'::public.anchor_level,'Frequent visible corrections, contradictions, misreads, or loss of composure undermine trust in the delivery.',0,4),
('nd-accuracy','Competent'::public.anchor_level,'Delivery is mostly accurate and composed, with minor recoverable slips that do not materially disrupt understanding.',5,8),
('nd-accuracy','Excellent'::public.anchor_level,'Delivery is consistently precise and composed, with clean recovery from any minor slip and no material internal inconsistency.',9,10),
('bp-problem','Low'::public.anchor_level,'The problem is vague, weakly evidenced, or disconnected from the proposed solution.',0,4),
('bp-problem','Competent'::public.anchor_level,'The problem is understandable and the solution addresses it credibly, though the fit or urgency could be sharper.',5,8),
('bp-problem','Excellent'::public.anchor_level,'The problem is specific and compelling, and the solution is clearly shown to address its core causes or needs.',9,10),
('bp-value','Low'::public.anchor_level,'The audience cannot clearly tell what is being offered, for whom, or why it is valuable.',0,4),
('bp-value','Competent'::public.anchor_level,'The offer, target user, and primary benefit are clear, though differentiation or concise articulation may be limited.',5,8),
('bp-value','Excellent'::public.anchor_level,'The value proposition is concise, specific, audience-centered, and immediately communicates what is offered and why it matters.',9,10),
('bp-traction','Low'::public.anchor_level,'The pitch provides little observable evidence of traction, feasibility, market interest, or reasons for an investor/buyer to engage.',0,4),
('bp-traction','Competent'::public.anchor_level,'Provides credible indicators of traction, feasibility, or opportunity and gives the audience a reasonable basis for interest.',5,8),
('bp-traction','Excellent'::public.anchor_level,'Presents compelling, well-framed evidence of traction or opportunity and translates it into a strong, credible case for investor/buyer interest.',9,10),
('bp-diff','Low'::public.anchor_level,'The pitch does not explain how the offer differs meaningfully from alternatives or why that difference matters.',0,4),
('bp-diff','Competent'::public.anchor_level,'Identifies relevant differentiators and explains their value, though the competitive case may be somewhat generic or incomplete.',5,8),
('bp-diff','Excellent'::public.anchor_level,'Defines clear, defensible differentiation and connects it directly to customer/investor value in a way that is difficult to confuse with alternatives.',9,10),
('gp-sync','Low'::public.anchor_level,'Speech and visible presentation media are frequently out of sync, causing confusion or forcing the audience to reconcile mismatched information.',0,4),
('gp-sync','Competent'::public.anchor_level,'Speech generally aligns with the visible media, with only occasional timing or reference mismatches.',5,8),
('gp-sync','Excellent'::public.anchor_level,'Speech and media are tightly synchronized, with visual changes and verbal references reinforcing each other at the right moments.',9,10),
('gp-continuity','Low'::public.anchor_level,'Media changes fragment the narrative or introduce content without clear connection to the spoken message.',0,4),
('gp-continuity','Competent'::public.anchor_level,'The narrative remains mostly coherent across media changes, with only minor disconnected or redundant elements.',5,8),
('gp-continuity','Excellent'::public.anchor_level,'All media elements contribute to one coherent narrative, with each transition extending rather than interrupting the spoken message.',9,10),
('gp-visual','Low'::public.anchor_level,'The speaker relies heavily on reading visible text or uses visuals that add little beyond duplicating speech.',0,4),
('gp-visual','Competent'::public.anchor_level,'Visuals generally support rather than replace the spoken message, with occasional over-reliance on reading or duplication.',5,8),
('gp-visual','Excellent'::public.anchor_level,'Visuals add complementary information while the speaker explains, interprets, or contextualizes them without simply reading them aloud.',9,10),
('gp-pacing','Low'::public.anchor_level,'Visual/media changes are too fast, too slow, dense, or poorly timed for the audience to process comfortably.',0,4),
('gp-pacing','Competent'::public.anchor_level,'Media pacing is generally manageable and accessible, with only occasional rushed, delayed, or overly dense moments.',5,8),
('gp-pacing','Excellent'::public.anchor_level,'Media pacing consistently gives the audience enough time and context to process each visual element without interrupting presentation momentum.',9,10),
('ap-terminology','Low'::public.anchor_level,'Specialized terms are used inaccurately, inconsistently, or without enough explanation for the intended academic audience.',0,4),
('ap-terminology','Competent'::public.anchor_level,'Terminology is mostly precise and appropriate, with minor imprecision or occasional missed explanation.',5,8),
('ap-terminology','Excellent'::public.anchor_level,'Specialized terminology is consistently precise, contextually appropriate, and explained whenever audience comprehension requires it.',9,10),
('ap-methodology','Low'::public.anchor_level,'The presented method is unclear, internally inconsistent, or insufficiently justified for the stated objective.',0,4),
('ap-methodology','Competent'::public.anchor_level,'The method is understandable and reasonably justified, with most key design choices explained well enough to defend.',5,8),
('ap-methodology','Excellent'::public.anchor_level,'The method is presented clearly and defensibly, with key choices, limitations, and their relationship to the objective articulated precisely.',9,10),
('ap-evidence','Low'::public.anchor_level,'Important claims lack visible/mentioned support, evidence is poorly connected to claims, or attribution is materially unclear.',0,4),
('ap-evidence','Competent'::public.anchor_level,'Most important claims are supported with relevant evidence or attribution, with minor gaps in precision or integration.',5,8),
('ap-evidence','Excellent'::public.anchor_level,'Evidence and attribution are used consistently and precisely, with clear links between sources/data and the claims they support.',9,10),
('ap-findings','Low'::public.anchor_level,'Findings are unclear, overstated, or disconnected from the evidence/method presented.',0,4),
('ap-findings','Competent'::public.anchor_level,'Findings are understandable and mostly supported by the presented evidence, with minor overreach or under-explanation.',5,8),
('ap-findings','Excellent'::public.anchor_level,'Findings are stated precisely, proportionately, and directly tied to the presented evidence and methodological context.',9,10),
('cr-bluf','Low'::public.anchor_level,'The main business conclusion or decision need is delayed, buried, or unclear.',0,4),
('cr-bluf','Competent'::public.anchor_level,'The main conclusion or decision need appears early enough and guides most of the report, though it could be sharper.',5,8),
('cr-bluf','Excellent'::public.anchor_level,'The key conclusion, implication, or decision need is presented immediately and clearly, giving the audience a strong frame for everything that follows.',9,10),
('cr-translation','Low'::public.anchor_level,'Data is recited or shown without sufficient interpretation, leaving business meaning unclear.',0,4),
('cr-translation','Competent'::public.anchor_level,'Most data is translated into understandable business meaning, though some figures remain insufficiently interpreted.',5,8),
('cr-translation','Excellent'::public.anchor_level,'Complex data is consistently converted into concise, decision-relevant meaning without losing important nuance.',9,10),
('cr-insight','Low'::public.anchor_level,'Observations remain descriptive and do not lead to useful implications or actions.',0,4),
('cr-insight','Competent'::public.anchor_level,'Identifies useful business implications and some actionable insights, though prioritization or specificity may be limited.',5,8),
('cr-insight','Excellent'::public.anchor_level,'Extracts clear, prioritized, actionable insights that directly connect evidence to business implications.',9,10),
('cr-recommendation','Low'::public.anchor_level,'Recommendations are absent, vague, unsupported, or not framed as decisions.',0,4),
('cr-recommendation','Competent'::public.anchor_level,'Provides practical recommendations linked to the presented analysis, though trade-offs or priorities may be underdeveloped.',5,8),
('cr-recommendation','Excellent'::public.anchor_level,'Provides specific, prioritized, decision-ready recommendations clearly justified by the presented evidence and business context.',9,10),
('info-balance','Low'::public.anchor_level,'Entertainment overwhelms useful information, or information is delivered so dryly that the intended infotainment format is not achieved.',0,4),
('info-balance','Competent'::public.anchor_level,'Maintains a workable balance between useful information and entertainment, with occasional imbalance.',5,8),
('info-balance','Excellent'::public.anchor_level,'Integrates information and entertainment seamlessly so each strengthens the other without sacrificing clarity or substance.',9,10),
('info-progression','Low'::public.anchor_level,'Progression drags, jumps erratically, or repeats material, weakening momentum.',0,4),
('info-progression','Competent'::public.anchor_level,'Maintains generally brisk progression with a coherent sequence, despite occasional slow or abrupt sections.',5,8),
('info-progression','Excellent'::public.anchor_level,'Maintains energetic, coherent progression throughout, moving quickly without sacrificing comprehension.',9,10),
('info-triggers','Low'::public.anchor_level,'Uses few meaningful devices to renew attention, or uses hooks/cues that feel repetitive or disconnected.',0,4),
('info-triggers','Competent'::public.anchor_level,'Uses relevant questions, contrasts, reveals, examples, or other engagement devices at useful points, though impact varies.',5,8),
('info-triggers','Excellent'::public.anchor_level,'Uses varied, well-timed engagement triggers that repeatedly renew attention while advancing the informational purpose.',9,10),
('info-energy','Low'::public.anchor_level,'On-camera presence is persistently flat, forced, or visually disengaged in ways that weaken the intended content style.',0,4),
('info-energy','Competent'::public.anchor_level,'Shows an engaging, appropriate personality and visual energy with only occasional flat or overdone moments.',5,8),
('info-energy','Excellent'::public.anchor_level,'Sustains an authentic, distinctive, and visually engaging presence that strengthens the content without overpowering the information.',9,10),
('al-outcomes','Low'::public.anchor_level,'Learners are not given a clear sense of what they should understand or be able to do.',0,4),
('al-outcomes','Competent'::public.anchor_level,'Learning outcomes are mostly clear and reflected in the content, though they may be broad or not consistently signposted.',5,8),
('al-outcomes','Excellent'::public.anchor_level,'Learning outcomes are explicit, focused, and visibly guide the content, examples, and final takeaway.',9,10),
('al-sequence','Low'::public.anchor_level,'Instruction is poorly ordered, skips prerequisites, or introduces ideas before needed foundations.',0,4),
('al-sequence','Competent'::public.anchor_level,'Instruction follows a mostly logical learning sequence with adequate scaffolding and only minor ordering issues.',5,8),
('al-sequence','Excellent'::public.anchor_level,'Instruction is deliberately scaffolded from prerequisite knowledge to more complex understanding, with each stage preparing for the next.',9,10),
('al-checkin','Low'::public.anchor_level,'The speaker advances without meaningful pauses, recaps, questions, or checks that help learners consolidate understanding.',0,4),
('al-checkin','Competent'::public.anchor_level,'Includes useful check-ins or recaps at several appropriate points, though timing or consistency could improve.',5,8),
('al-checkin','Excellent'::public.anchor_level,'Uses well-timed, purposeful check-ins, recaps, or reflective prompts that help learners consolidate understanding before progressing.',9,10),
('al-takeaway','Low'::public.anchor_level,'The lesson ends without a clear synthesis of what learners should retain or apply.',0,4),
('al-takeaway','Competent'::public.anchor_level,'Provides a clear summary or takeaway that captures most essential learning, though application may be somewhat general.',5,8),
('al-takeaway','Excellent'::public.anchor_level,'Ends with a concise, memorable synthesis that clearly states what learners should retain, connect, or apply next.',9,10),
('mkt-painpoint','Low'::public.anchor_level,'The audience problem is vague, generic, or poorly connected to the target audience''s observable needs.',0,4),
('mkt-painpoint','Competent'::public.anchor_level,'Identifies a relevant audience pain point and connects it reasonably to the offer, though specificity or urgency may be limited.',5,8),
('mkt-painpoint','Excellent'::public.anchor_level,'Frames a specific, audience-relevant pain point compellingly and makes its importance immediately clear.',9,10),
('mkt-payoff','Low'::public.anchor_level,'The audience cannot clearly tell what benefit or outcome the product/service provides.',0,4),
('mkt-payoff','Competent'::public.anchor_level,'The primary payoff is understandable and relevant, though some benefits are generic or insufficiently prioritized.',5,8),
('mkt-payoff','Excellent'::public.anchor_level,'Communicates a specific, credible, audience-centered payoff that makes the value of the product/service immediately understandable.',9,10),
('mkt-drivers','Low'::public.anchor_level,'The presentation lacks a clear reason, incentive, proof point, or call that would move the audience toward action.',0,4),
('mkt-drivers','Competent'::public.anchor_level,'Uses relevant conversion drivers such as proof, urgency, benefits, or calls to action, though effectiveness or integration varies.',5,8),
('mkt-drivers','Excellent'::public.anchor_level,'Combines persuasive conversion drivers strategically and ethically to create a clear, credible path from interest to action.',9,10),
('mkt-alignment','Low'::public.anchor_level,'Tone, claims, positioning, or call to action feel inconsistent with the presented brand or offer.',0,4),
('mkt-alignment','Competent'::public.anchor_level,'Message is generally consistent with the presented brand/offer, with only minor tonal or positioning mismatches.',5,8),
('mkt-alignment','Excellent'::public.anchor_level,'Tone, value proposition, claims, and call to action are consistently aligned with a coherent brand/offer identity throughout.',9,10);

do $$ begin if (select count(*) from public.paths) <> 3 then raise exception 'Expected 3 paths'; end if; if (select count(*) from public.tracks) <> 13 then raise exception 'Expected 13 tracks'; end if; if (select count(*) from public.criteria) <> 64 then raise exception 'Expected 64 criteria'; end if; if (select count(*) from public.criterion_anchors) <> 192 then raise exception 'Expected 192 criterion anchors'; end if; end $$;