export const portalRoutePaths = {
  foundation: '/',
  authentication: {
    root: '/auth',
    signIn: '/auth/sign-in',
    roleAuthorization: '/auth/role-authorization',
    emailVerification: '/auth/email-verification',
    accessUnavailable: '/auth/access-unavailable',
    forgotPassword: '/auth/forgot-password',
    resetLinkSent: '/auth/reset-link-sent',
    resetPassword: '/auth/reset-password',
    passwordResetComplete: '/auth/password-reset-complete',
  },
  volunteer: {
    root: '/volunteer',
    assignments: '/volunteer/assignments',
    assignedTask: '/volunteer/assignments/sub-8821',
    declineAssignment: '/volunteer/assignments/sub-8821/decline',
    activeAssignmentsAfterDecline: '/volunteer/assignments/after-decline',
    availability: '/volunteer/availability',
    availabilityUnavailable: '/volunteer/availability/unavailable',
    scoringWorkspace: '/volunteer/evaluation/sub-8821',
    criterionFeedback: '/volunteer/evaluation/sub-8821/criterion',
    finalSubmission: '/volunteer/evaluation/sub-8821/review',
    evaluationSubmitted: '/volunteer/evaluation/sub-8821/submitted',
    completedHistory: '/volunteer/completed',
    completedPendingModeration: '/volunteer/completed/sub-8821',
    completedApproved: '/volunteer/completed/sub-8792',
    completedRejected: '/volunteer/completed/sub-8755',
    completedProcessing: '/volunteer/completed/sub-8741',
    reopenedEvaluation: '/volunteer/evaluation/sub-8821/reopened',
  },
  admin: {
    root: '/admin',
    dashboard: '/admin/dashboard',
    requests: '/admin/requests',
    requestDetailsRouting: '/admin/requests/req-1042',
    assignmentPicker: '/admin/requests/req-1042/assign',
    confirmReassignment: '/admin/requests/req-1042/reassign',
    requestAssignedAi: '/admin/requests/req-1041',
    requestRedirectedHuman: '/admin/requests/req-1034',
    evaluations: '/admin/evaluations',
    evaluationProcessingHuman: '/admin/evaluations/sub-8834',
    evaluationApprovedAi: '/admin/evaluations/sub-8798',
    moderation: '/admin/moderation',
    moderationReview: '/admin/moderation/sub-8821',
    confirmModerationApproval: '/admin/moderation/sub-8821/approve',
    confirmModerationRejection: '/admin/moderation/sub-8821/reject',
    requestReReview: '/admin/moderation/sub-8821/re-review',
    volunteers: '/admin/volunteers',
    inviteVolunteer: '/admin/volunteers/invite',
    volunteerAccount: '/admin/volunteers/farhana',
    availabilityOverride: '/admin/volunteers/farhana/availability',
    volunteerTrackEligibility: '/admin/volunteers/farhana/tracks',
    events: '/admin/events',
    eventEditor: '/admin/events/editor',
    audit: '/admin/audit',
  },
  superAdmin: {
    root: '/super-admin',
  },
} as const

export type PortalJourney =
  | 'authentication'
  | 'volunteer'
  | 'admin'
  | 'superAdmin'
